---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  - pip install ansible
  - cd tests

script:
  - "ansible-playbook playbook.yml --syntax-check"
  - "ansible-playbook playbook.yml --connection=local"
  - >
    ansible-playbook playbook.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - "curl http://localhost/"
